# Generated by Django 5.0.6 on 2024-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/illustration/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
